services:
    app:
        container_name: flask-akk
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - otel-collector
        environment:
          - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
          - OTEL_EXPORTER_OTLP_INSECURE=true
          - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
          - OTEL_SERVICE_NAME=flask-app
          - OTEL_LOG_LEVEL=DEBUG

    otel-collector:
        image: otel/opentelemetry-collector-contrib:0.117.0
        volumes:
            - ./otel-collector.config.yml:/etc/otelcol-contrib/config.yaml
        ports:
            - 4317:4317
            - 4318:4318