receivers:
    otlp:
        protocols:
            http:
                endpoint: 0.0.0.0:4318
            grpc:
                endpoint: 0.0.0.0:4317

processors:
    batch:
        timeout: 10s

exporters:
    otlphttp/logs:
        endpoint: https://api.lognegar.ir/api
        headers:
            lognegar-api-key: <YOUR_API_KEY>
    otlphttp/traces:
        endpoint: https://api.lognegar.ir/api
        headers:
            lognegar-api-key: <YOUR_API_KEY>
    otlphttp/metrics:
        endpoint: https://api.lognegar.ir/api
        headers:
            lognegar-api-key: <YOUR_API_KEY>
service:
    pipelines:
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp/logs]
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp/traces]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp/metrics]
